### ISSUE TITLE
No support for regular expressions.

### ISSUE THREAD

**Issue by DylanSijanivandi** [Swivelgames/copy-find-results#1]
In my case, I wanted to copy all text within speech marks using ```"(.*?)"```, however it explicitly listed results for "(.*?)" as opposed to the found text.

**Comment by Swivelgames** [comment]
@COSMO-D- Very interesting! Thanks for bringing this up. I'll take a look at this and update it if I find anything peculiar.

Can you run `apm list` and post the output?

**Comment by Swivelgames** [comment]
Hey @COSMO-D- 

What version of Atom are you using?

I just tried running this and it seemed to work correctly:

```
Results for ""(.*?)"" in "client/actions"

/****/client/actions/Modals/index.js:
  25:   * If "force" is set to true, the modal stack will be cleared/emptied.

```

![image](https://user-images.githubusercontent.com/1456302/45260981-6f28c800-b3bb-11e8-877e-701e44a0013e.png)

**Comment by DylanSijanivandi** [comment]
I'm running Atom 1.30.0
No worries though, I found another way to achieve what your package does. I can just press ALT+ENTER to highlight the found text, then copy and paste it into a new file.

**Comment by Swivelgames** [comment]
@COSMO-D- Glad you found a solution!

**Comment by JurgenG** [comment]
Also having this issue, running Atom 1.41.0-beta1 x64 on MacOS.

This was the Regex I'm searching on: [a-z]+\.[a-z]+\n (basically domains at the end of a line - stripping all the subdomains)

**Comment by Swivelgames** [comment]
@JurgenG Stupid question, but are you getting results back for this search?

I'm going to dive into this a bit more today.

**Comment by JurgenG** [comment]
Sure, the regex worked fine enough (one domain per line, no addon TLD's like .co.uk)
This text:
mydomain.domain.com
happy.meals.com
play.that.funky.music.right.now

Results in finding:
domain.com
meals.com
right.now
