### ISSUE TITLE
How to copy collapsed results?

### ISSUE THREAD

**Issue by banar** [Swivelgames/copy-find-results#4]
It would be really great to be able to copy collapsed results.

**Comment by Swivelgames** [comment]
Hey @banar,

By default, collapsed results should be copied. If you would like to disable this, you can check the boxes in settings:

![image](https://user-images.githubusercontent.com/1456302/46765147-ea73e700-cca3-11e8-8d5c-fe56467a83af.png)

If disabling these settings doesn't fix the issue, can you post some reproduction steps for the bug?

Thanks!
